# Generated by Django 3.1.5 on 2021-01-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BCname', models.CharField(max_length=50, unique=True)),
                ('BCid', models.IntegerField(default=0)),
                ('BC_shops', models.IntegerField(default=0)),
                ('BC_sales', models.IntegerField(default=0)),
                ('BC_marks', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('city_code', models.CharField(blank=True, max_length=10, null=True)),
                ('EHR_name', models.CharField(blank=True, max_length=20, null=True)),
                ('EHR_code', models.CharField(blank=True, max_length=20, null=True)),
                ('EHR_shop', models.CharField(blank=True, max_length=20, null=True)),
                ('EHR_address', models.CharField(blank=True, max_length=50, null=True)),
                ('EHR_status', models.CharField(blank=True, max_length=10, null=True)),
                ('connect_status', models.CharField(blank=True, max_length=10, null=True)),
                ('sign_status', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_type', models.CharField(blank=True, max_length=10, null=True)),
                ('business_type', models.CharField(blank=True, max_length=10, null=True)),
                ('brand_type', models.CharField(blank=True, max_length=10, null=True)),
                ('CA_name', models.CharField(blank=True, max_length=10, null=True)),
                ('coordinate_x', models.FloatField(blank=True, default=0, null=True)),
                ('coordinate_y', models.FloatField(blank=True, default=0, null=True)),
                ('license', models.CharField(blank=True, max_length=10, null=True)),
                ('shopFkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermap.businesscircle')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_circle', models.CharField(blank=True, max_length=50, null=True)),
                ('coordinate_x', models.FloatField(default=0)),
                ('coordinate_y', models.FloatField(default=0)),
                ('coordinateFkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermap.businesscircle')),
            ],
        ),
    ]
