# Generated by Django 3.1.5 on 2021-01-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscircle',
            name='BC_marks',
        ),
        migrations.RemoveField(
            model_name='businesscircle',
            name='BC_sales',
        ),
        migrations.RemoveField(
            model_name='businesscircle',
            name='BC_shops',
        ),
        migrations.RemoveField(
            model_name='businesscircle',
            name='BCid',
        ),
    ]
