# Generated by Django 3.1.5 on 2021-01-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0002_auto_20210112_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='CA_name',
            new_name='AECA',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='EHR_code',
            new_name='AECA_code',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='EHR_status',
            new_name='AECAzongjian',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='EHR_name',
            new_name='AECAzongjian_code',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='business_type',
            new_name='bk_dabu',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='city',
            new_name='bk_daqu',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='city_code',
            new_name='circle',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='connect_status',
            new_name='dabu',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='license',
            new_name='daqu',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_type',
            new_name='guishu_area',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='sign_status',
            new_name='is_circle',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='EHR_shop',
            new_name='shop_code',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='EHR_address',
        ),
        migrations.AddField(
            model_name='shop',
            name='jieyue_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='lianjia_dabu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='lianjia_daqu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shiye_dabu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shiye_daqu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='coordinate_x',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='coordinate_y',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
