# Generated by Django 3.1.5 on 2021-01-15 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0004_businesscircle_count_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resblock_id', models.CharField(blank=True, max_length=20, null=True)),
                ('resblock_name', models.CharField(blank=True, max_length=20, null=True)),
                ('district_name', models.CharField(blank=True, max_length=10, null=True)),
                ('bizcircle_name', models.CharField(blank=True, max_length=10, null=True)),
                ('building_longitude', models.FloatField(blank=True, default=0, null=True)),
                ('building_latitude', models.FloatField(blank=True, default=0, null=True)),
                ('sign_date', models.CharField(blank=True, max_length=20, null=True)),
                ('biz_type', models.CharField(blank=True, max_length=10, null=True)),
                ('subbiz_type', models.CharField(blank=True, max_length=10, null=True)),
                ('agreement_id', models.CharField(blank=True, max_length=20, null=True)),
                ('deal_price', models.FloatField(blank=True, default=0, null=True)),
                ('commission', models.FloatField(blank=True, default=0, null=True)),
                ('area', models.FloatField(blank=True, default=0, null=True)),
                ('blockFkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermap.businesscircle')),
            ],
        ),
    ]
