# Generated by Django 3.1.5 on 2021-01-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0005_resblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resblock',
            name='resblock_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resblock',
            name='subbiz_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
