# Generated by Django 3.1.5 on 2021-01-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0007_auto_20210115_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='resblock_st',
            name='resblock_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
