# Generated by Django 3.1.5 on 2021-01-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0008_resblock_st_resblock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resblock_st',
            name='sign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
