# Generated by Django 3.1.5 on 2021-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0009_auto_20210120_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resblock_st',
            name='sign_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
