# Generated by Django 3.1.5 on 2021-01-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0010_auto_20210120_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resblock',
            name='resblock_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
