# Generated by Django 3.1.5 on 2021-01-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0013_auto_20210120_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resblock_st',
            old_name='area',
            new_name='gmv',
        ),
        migrations.RemoveField(
            model_name='resblock_st',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='resblock_st',
            name='deal_price',
        ),
        migrations.AddField(
            model_name='resblock_st',
            name='resblock_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
