# Generated by Django 3.1.5 on 2021-02-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0017_auto_20210127_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='draw_bk_daqu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='draw_lianjia_daqu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
